Impact Analysis - CMS142
alphora/air-ecqm-sandbox pull request #19
Opened 2024-10-10 18:42 UTC by soy-park

Impact analysis of QICore6 uplift on **CMS142** (_Diabetic Retinopathy: Communication with the Physician Managing Ongoing Diabetes Care_)
- Added comment to update 'Condition' to 'ConditionProblemsHealthConcerns'
- Added comments to update 'Observation' to 'ObservationClinicalResult'

2024-10-10 19:20 UTC, guptava approved these changes

2024-10-16 19:22 UTC, jbyrdevans requested changes

2024-10-16 19:22 UTC, jbyrdevans commented on input/cql/DRCommunicationWithPhysicianManagingDiabetesFHIR.cql
> +*/
Should this be a union of ConditionProblemsHealthConcerns and ConditionEncounterDiagnosis?

2024-11-12 22:29 UTC, jbyrdevans approved these changes

2024-11-12 22:30 UTC, merged